[docs] update the Android build guide to set up NDK
openthread/ot-commissioner pull request #244
Opened 2024-03-27 08:31 UTC by wgtdkp

The guide doc is outdated on the NDK part.

Fixes issue: https://github.com/openthread/ot-commissioner/issues/243

2024-03-28 04:49 UTC, librasungirl approved these changes
👍

2024-03-28 22:52 UTC, Vyrastas requested changes

2024-03-28 22:52 UTC, Vyrastas commented on android/BUILDING.md
> +- Install Android NDK by following https://developer.android.com/studio/projects/install-ndk#default-version
```suggestion
- Install Android NDK by following https://developer.android.com/studio/projects/install-ndk#default-version.
```

2024-03-28 22:52 UTC, Vyrastas commented on android/BUILDING.md
> +> 1.  you need to set env `ANDROID_ABI` to the ABI of your phone. This value can be got with command `adb shell getprop ro.product.cpu.abi` after connecting the phone to your computer.
```suggestion
> 1.  You need to set `ANDROID_ABI` to the ABI of your phone. This value can be retrieved using the command `adb shell getprop ro.product.cpu.abi` after connecting the phone to your computer.
```

2024-03-28 22:52 UTC, Vyrastas commented on android/BUILDING.md
> +> 2.  you need to set `ANDROID_NDK_HOME` to your Android NDK directory. This is typically `$HOME/Android/sdk/ndk/xx.x.xxxxx` (where `xx.x.xxxxx` is the NDK version) on Linux and Mac OS or `$HOME/Libr
```suggestion
> 2.  You need to set `ANDROID_NDK_HOME` to your Android NDK directory. This is typically `$HOME/Android/sdk/ndk/xx.x.xxxxx` (where `xx.x.xxxxx` is the NDK version) on Linux and Mac OS or `$HOME/Library/Android/sdk/ndk-bundle` on older OS versions.
```

2024-03-29 14:57 UTC, Vyrastas approved these changes

2024-03-29 17:55 UTC, jwhui approved these changes

2024-03-29 17:56 UTC, merged